package cods;


import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class JanelaProdutos extends javax.swing.JFrame {

    private static JanelaProdutos janelaProd1 = new JanelaProdutos();
    
    /**
     * Creates new form Main
     */
    public JanelaProdutos() {
        initComponents();
    }
    
    public static JanelaProdutos getJanelaProd(){
        if(janelaProd1 == null){
            janelaProd1 = new JanelaProdutos();
        }
        return janelaProd1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstrumentoMusical = new javax.swing.JLabel();
        btGuitarra = new javax.swing.JButton();
        btViolao = new javax.swing.JButton();
        btBaixo = new javax.swing.JButton();
        btItem = new javax.swing.JToggleButton();
        btSair = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuTabelas = new javax.swing.JMenu();
        MnItemTabProd = new javax.swing.JMenuItem();
        MnItemTabGuit = new javax.swing.JMenuItem();
        MnItemTabViolao = new javax.swing.JMenuItem();
        MnItemTabBaixo = new javax.swing.JMenuItem();
        MnItemItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Produtos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInstrumentoMusical.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInstrumentoMusical.setForeground(new java.awt.Color(255, 255, 255));
        lblInstrumentoMusical.setText("Instrumento Músical");
        getContentPane().add(lblInstrumentoMusical, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 102));

        btGuitarra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btGuitarra.setText("Guitarra");
        btGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuitarraActionPerformed(evt);
            }
        });
        getContentPane().add(btGuitarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        btViolao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btViolao.setText("Violão");
        btViolao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViolaoActionPerformed(evt);
            }
        });
        getContentPane().add(btViolao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 92, -1));

        btBaixo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btBaixo.setText("Baixo");
        btBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBaixoActionPerformed(evt);
            }
        });
        getContentPane().add(btBaixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 92, -1));

        btItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btItem.setText("Item");
        btItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btItemActionPerformed(evt);
            }
        });
        getContentPane().add(btItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 92, -1));

        btSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/39e5fe1aa42d87d29fd9810faa6afba2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        MenuTabelas.setText("Tabelas");

        MnItemTabProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/package.png"))); // NOI18N
        MnItemTabProd.setText("Tabela Produto");
        MnItemTabProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemTabProdActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemTabProd);

        MnItemTabGuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/electric-guitar.png"))); // NOI18N
        MnItemTabGuit.setText("Tabela Guitarra");
        MnItemTabGuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemTabGuitActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemTabGuit);

        MnItemTabViolao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/guitar-instrument.png"))); // NOI18N
        MnItemTabViolao.setText("Tabela Violão");
        MnItemTabViolao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemTabViolaoActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemTabViolao);

        MnItemTabBaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bass-guitar.png"))); // NOI18N
        MnItemTabBaixo.setText("Tabela Baixo");
        MnItemTabBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemTabBaixoActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemTabBaixo);

        MnItemItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plectrum.png"))); // NOI18N
        MnItemItem.setText("Tabela Item");
        MnItemItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemItemActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemItem);

        MenuPrincipal.add(MenuTabelas);

        setJMenuBar(MenuPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuitarraActionPerformed
        JanelaGuit.getJanelaGuit().setVisible(true);
    }//GEN-LAST:event_btGuitarraActionPerformed

    private void btViolaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViolaoActionPerformed
        JanelaViolao.getJanelaViolao().setVisible(true);
    }//GEN-LAST:event_btViolaoActionPerformed

    private void btBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBaixoActionPerformed
        JanelaBaixo.getJanelaBaixo().setVisible(true);
    }//GEN-LAST:event_btBaixoActionPerformed

    private void MnItemTabGuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemTabGuitActionPerformed
        TabGuit.getTabGuit().setVisible(true);
        TabGuit.listarTab1();
    }//GEN-LAST:event_MnItemTabGuitActionPerformed

    private void MnItemTabViolaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemTabViolaoActionPerformed
        TabViolao.getTabViolao().setVisible(true);
        TabViolao.listarTab1();
    }//GEN-LAST:event_MnItemTabViolaoActionPerformed

    private void MnItemTabBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemTabBaixoActionPerformed
        TabBaixo.getTabBat().setVisible(true);
        TabBaixo.listarTab1();
    }//GEN-LAST:event_MnItemTabBaixoActionPerformed

    private void MnItemTabProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemTabProdActionPerformed
        TabProduto.getTabProd().setVisible(true);
        TabProduto.listarTab1();
    }//GEN-LAST:event_MnItemTabProdActionPerformed

    private void btItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btItemActionPerformed
        JanelaItem.getJanelaItem().setVisible(true);
    }//GEN-LAST:event_btItemActionPerformed

    private void MnItemItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemItemActionPerformed
        TabItem.getTabItem().setVisible(true);
        TabItem.listarTab1();
    }//GEN-LAST:event_MnItemItemActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
        Inicio in = new Inicio();
        in.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Inicio in = new Inicio();
        in.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, 
                "Deseja Sair?", 
                "Sair", 
                JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuTabelas;
    private javax.swing.JMenuItem MnItemItem;
    private javax.swing.JMenuItem MnItemTabBaixo;
    private javax.swing.JMenuItem MnItemTabGuit;
    private javax.swing.JMenuItem MnItemTabProd;
    private javax.swing.JMenuItem MnItemTabViolao;
    private javax.swing.JButton btBaixo;
    private javax.swing.JButton btGuitarra;
    private javax.swing.JToggleButton btItem;
    private javax.swing.JToggleButton btSair;
    private javax.swing.JButton btViolao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInstrumentoMusical;
    // End of variables declaration//GEN-END:variables
}
